### ISSUE TITLE
Breaking changes in 0.4.4

### ISSUE THREAD

**Issue by dougmoscrop** [AndrewKeig/express-validation#20]
Hi there,

It seems like in 0.4.3 to 0.4.4 req.query is manipulated now so that it is parsed, so anywhere that we have code that, after validation, might JSON.parse(req.query.xyz) it will already be an object. This can be dealt with defensively, but not sure I want my validation to manipulate my request and if I do, should probably go under a major version bump?

**Comment by colthreepv** [comment]
You are indeed right @dougmoscrop, I tested a little and discovered that [this simple line](https://github.com/AndrewKeig/express-validation/blob/master/lib/index.js#L63) does way more than expected.

It was definitely a mistake, I am uncertain if roll back is possible for 0.4.x or if it's even a good idea to do that.

Next release will be surely `0.5`, with some tests checking for req parsing.
Do you have any suggestions about how to fix this otherwise?

**Comment by AndrewKeig** [comment]
Are you happy for me to push this to npm?

**Comment by colthreepv** [comment]
mmm no Andrew I'd rather be more careful and pull out a refined and documented 0.5

**Comment by AndrewKeig** [comment]
Fair enough, let us know when your ready.
